Improved error handling

diff --git a/check_linux_uptime b/check_linux_uptime
--- a/check_linux_uptime
+++ b/check_linux_uptime
@@ -1,6 +1,11 @@
 #!/bin/bash
 
 response=$(ssh nagios@$1 "/usr/bin/uptime" | cut -d',' -f 1 | cut -c 11-)
+if [[ -z $response ]]
+then
+	echo "SSH Error"
+	exit 3
+fi
 
 if [[ $response = *"min"* ]]
 then
@@ -18,3 +23,4 @@ else
 fi
 
 echo "$response | DurationInMinutes=$perfData"
+exit 0
