Improved error handling

diff --git a/check_aix_cpu b/check_aix_cpu
--- a/check_aix_cpu
+++ b/check_aix_cpu
@@ -36,6 +36,12 @@ done
 
 command="vmstat 1 3 | awk '{ print \$14\" \"\$15\" \"\$16\" \"\$17\" \"\$18 }' | tail -1"
 output=$(ssh nagios@$host "$command")
+if [[ -z $output ]]
+then
+	echo "SSH Error"
+	exit 3
+fi
+
 us=$(echo $output | cut -d " " -f1 )
 sy=$(echo $output | cut -d " " -f2 )
 id=$(echo $output | cut -d " " -f3 )
diff --git a/check_aix_mem b/check_aix_mem
--- a/check_aix_mem
+++ b/check_aix_mem
@@ -35,6 +35,12 @@ do
 done
 
 output=$(ssh nagios@$host "vmstat -v")
+if [[ -z $output ]]
+then
+	echo "SSH Error"
+	exit 3
+fi
+
 value_numperm=$(echo "$output" | grep numperm | awk '{print $1}'| sed s/\s+//g)
 value_inuse=$(echo "$output" | grep "percentage of memory" | sed s/\s+//g | awk '{print $1}')
 
diff --git a/check_linux_cpu_info b/check_linux_cpu_info
--- a/check_linux_cpu_info
+++ b/check_linux_cpu_info
@@ -1,6 +1,11 @@
 #!/bin/bash
 
 rawOutput=$(ssh nagios@$1 "lscpu")
+if [[ -z $rawOutput ]]
+then
+	echo "SSH Error"
+	exit 3
+fi
 
 totalCores=$(echo "{$rawOutput}" | grep -m 1 "CPU(s):" | awk '{print $2}')
 sockets=$(echo "{$rawOutput}" | grep "Socket(s):" | awk '{print $2}')
diff --git a/check_linux_mem b/check_linux_mem
--- a/check_linux_mem
+++ b/check_linux_mem
@@ -39,6 +39,12 @@ valw=$(echo "$valw*1.0" | bc)
 
 
 output=$(ssh nagios@$host "free")
+if [[ -z $output ]]
+then
+	echo "SSH Error"
+	exit 3
+fi
+
 if [[ $output = *"-/+"* ]]
 then
 	totalMem=$(echo "$output" | grep "Mem" | awk '{print $2}')
diff --git a/check_linux_swap b/check_linux_swap
--- a/check_linux_swap
+++ b/check_linux_swap
@@ -38,6 +38,12 @@ valc=$(echo "$valc*1.0" | bc)
 valw=$(echo "$valw*1.0" | bc)
 
 output=$(ssh nagios@$host "free")
+if [[ -z $output ]]
+then
+	echo "SSH Error"
+	exit 3
+fi
+
 totalSwap=$(echo "$output" | grep "Swap" | awk '{print $2}')
 usedSwap=$(echo "$output" | grep "Swap" | awk '{print $3}')
 
diff --git a/check_linux_version b/check_linux_version
--- a/check_linux_version
+++ b/check_linux_version
@@ -1,6 +1,11 @@
 #!/bin/bash
 
 value=$(ssh nagios@$1 "cat /etc/*-release")
+if [[ -z $value ]]
+then
+	echo "SSH Error"
+	exit 3
+fi
 
 if [[ $value = *"release"* ]]; then
   value=$(echo "$value" | grep release | tail -n 1)
diff --git a/check_ntp_time b/check_ntp_time
--- a/check_ntp_time
+++ b/check_ntp_time
@@ -38,6 +38,12 @@ then
 fi
 
 ntp_config=`ssh nagios@$host "grep -w ^server /etc/ntp.conf"`
+if [[ -z $ntp_config ]]
+then
+	echo "SSH Error"
+	exit 3
+fi
+
 ntp_servers=`echo $ntp_config | sed -r 's/\b(iburst|server)\b//g'`
 
 for server in $ntp_servers
